## R programming Practice Exercises

In [7]:
## Assign operator

In [8]:
x <- 3

In [9]:
x

[1] 3

In [12]:
print(x)

[1] 3


In [19]:
# Comment in R

x <- 3 ## Assign value in x
x  # ptint the value of x


[1] 3

In [21]:
x <- 1:22

x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22

In [22]:
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22



### Matrices

In [23]:
m <- matrix(nrow = 2, ncol = 3)

m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [24]:
dim(m)

[1] 2 3

In [25]:
attributes(m)

$dim
[1] 2 3

In [27]:
# for the adding values in matric we use following 

m <- matrix(1:6, nrow=3, ncol=2)

m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [28]:
dim(m)

[1] 3 2

In [29]:
# we can directly assing values using vectors

m <- 1:12

m

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [30]:
dim(m) <-c(3,4) # 3 rows and 4 columns 

In [31]:
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

### Cbind and rbind to create matrix

In [32]:
x <- 1:3
y <- 10:12

cbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [33]:
# for row 

rbind(x,y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

### list in R

In [35]:
# As we know we can't create the vector of the list see in example

v <- c(1,3,4,TRUE, 'a',9)  ## you will noted that it use type casting to convert all value in to character

v

[1] "1"    "3"    "4"    "TRUE" "a"    "9"

In [36]:
# list example
v <- list(1,3,4,TRUE, 'a', 'c', 9) ## now this we sotore values in form of list

v

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 4

[[4]]
[1] TRUE

[[5]]
[1] "a"

[[6]]
[1] "c"

[[7]]
[1] 9

### Factor

In [37]:
x <- factor(c('yes', 'yes', 'no', 'yes','no')) ## this will create a factor

x  ## best thing it will tell about the level in output that we have two level yes and no

[1] yes yes no  yes no 
Levels: no yes

In [39]:
# let apply some fuction of the table

table(x) ## the table show the count value for data

x
 no yes 
  2   3 

In [40]:
#  Now apply another class which is unclass mean it will show value in numerics

unclass(x) 

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

In [44]:
attr(,"levels")

ERROR: Error in attr(, "levels"): argument 1 is empty


In [45]:
# level in factor

w <- factor(c("Sunday", "Monday", "Tuesday", "Wenesday", "Thrusday", "Friday", "saturday"))

w

[1] Sunday   Monday   Tuesday  Wenesday Thrusday Friday   saturday
Levels: Friday Monday saturday Sunday Thrusday Tuesday Wenesday

In [50]:
# Now use the level

w <- factor(c("Sunday", "Monday", "Tuesday", "Wenesday", "Thrusday", "Friday", "saturday"),
            levels = c("Monday", "Tuesday", "Wenesday", "Thrusday", "Friday", "saturday", "Sunday"))

w

[1] Sunday   Monday   Tuesday  Wenesday Thrusday Friday   saturday
Levels: Monday Tuesday Wenesday Thrusday Friday saturday Sunday

### Missing Values

In [51]:
# is.na for na mean null values

x <- c(1,2, 3, NA, 4, NA)

is.na(x)  ## for the null value mean NA it will show TURE 

[1] FALSE FALSE FALSE  TRUE FALSE  TRUE

In [52]:
is.nan(x)  ## this function will not detect the null values in the vector

[1] FALSE FALSE FALSE FALSE FALSE FALSE

In [53]:
x <- c (1,2, NaN, 4, NA, 7, NA, 8, NaN)

is.nan(x)  ## now you will see the TURE for the NAN only

[1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE

In [54]:
is.na(x) ## this function will detect all the null NaN and NA values 

[1] FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

### Data Frame

In [9]:
# create the a datafram

d <- data.frame(day = 1:4, rain = c(T,F,T,F))

d

day rain 
1 1    TRUE
2 2   FALSE
3 3    TRUE
4 4   FALSE

In [12]:
nrow(d)

[1] 4

In [13]:
ncol(d)

[1] 2

### Obeject_name

In [14]:
# so here we will try the example of the object names


In [16]:
x <- list( a = 1:4, b = "Awais", c = 'I am fine')
#x

x$b

$a
[1] 1 2 3 4

$b
[1] "Awais"

$c
[1] "I am fine"

[1] "Awais"

In [21]:
 m <- matrix(1:6, nrow =2  , ncol = 3)
dimname <- list(c('r1', 'rii', 'r3'), c('c1','cii', 'c3'))
 
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## Datatypes and operations 2

### subset

In [23]:
# example of subsetting of data

x <- c("a", 'b,','A', 'c', 'd','a', 'B', 'A')

x[1] # return the value of first index

[1] "a"

In [25]:
x[ x > 'a'] # the value of which greater then "a"

[1] "b," "A"  "c"  "d"  "B"  "A"

In [26]:
x[x > 'A']

[1] "b," "c"  "d"  "B"

In [27]:
x[ x > 'c']

[1] "d"

In [30]:
u <- x > 'b'

In [31]:
u[]

[1] FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE

### Subset of matrix

In [32]:
m <- matrix(1:6, 2,3)

m[1,2]

[1] 3

In [35]:
m[2,1]

[1] 2

In [36]:
m[,2]

[1] 3 4

In [38]:
x <- matrix(1:6, 2,3)

x[1,2]

[1] 3

In [40]:
x[1,2, drop= FALSE]

[,1]
[1,] 3

### subset of the list

In [42]:
# example of the list ot sub set

l <- list(weekend = 1:4, rain_pro = .6)

l[1]

$weekend
[1] 1 2 3 4

### Control structure 

In [1]:
#if_ else example


In [17]:
x <- 3
y <- 0

if (x > 2){
      y <- 10
        y
} else {
    y
}

[1] 10

In [18]:
#second method for above 

In [23]:
print(y <- if(x > 1){
    10
    y
} else {
    0
})

[1] 0


### control structur: For loop

In [25]:
# ist method to used to run for loop
x <- c('a', 'b','c','d','e','f')

for( i in 1:6){
    print(x[i])
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"
[1] "f"


In [26]:
# second method for loop

x <- c('a', 'b','c','d','e','f')
for (i in seq_along(x)){
    print(x[i])
}
    

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"
[1] "f"


In [29]:
# third method for loop

x <- c('a', 'b','c','d','e','f')

for(i in x){
    print(i)
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"
[1] "f"


### Control sturcture nested loop

In [44]:
# nested loop

x <- matrix(1:25, 5,5)

x


[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [47]:
y <- for(i in seq_len(ncol(x))) {
        for(j in seq_len(nrow(x))) {
            print(x[i, j])
    }
}

[1] 1
[1] 6
[1] 11
[1] 16
[1] 21
[1] 2
[1] 7
[1] 12
[1] 17
[1] 22
[1] 3
[1] 8
[1] 13
[1] 18
[1] 23
[1] 4
[1] 9
[1] 14
[1] 19
[1] 24
[1] 5
[1] 10
[1] 15
[1] 20
[1] 25


ERROR: Error in read.table(y): 'file' must be a character string or connection


### While loop

In [2]:
count <- 0 

while(count < 10) {
    print(count)
    count <- count+1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


In [3]:
# second example of while loop

In [13]:
z <- 5

while(z >= 3 && z<= 10) {
    print(z)
    coin <- rbinom(1,1,0.5)
    
    if(coin == 1) {
        z <- z+1
    }
    else {
        z <- z-1
    }
}

[1] 5
[1] 6
[1] 7
[1] 8
[1] 7
[1] 8
[1] 7
[1] 8
[1] 7
[1] 6
[1] 7
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


### Funtion in R

In [1]:
#R has some built in functions seq(), max(), min(), etc

# Create a sequence of numbers from 32 to 44.

print(seq(32,44))

 [1] 32 33 34 35 36 37 38 39 40 41 42 43 44


In [3]:
# Find mean of numbers from 25 to 82.
print(mean(25:82))

[1] 53.5


In [7]:
# Find sum of numbers frm 41 to 68.
print(sum(41:68))

[1] 1526


In [14]:
#User-defined Function
# Create a function to print squares of numbers in sequence.

func <- function(a){
    for(i in 1:a){
        print(b <- i^2)
    }
}


# Call the function new.function supplying 6 as an argument.
func(6)

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25
[1] 36


In [17]:
# another function with 3 aurguments

fun <- function(a,b,c) {
    res <- a*b-c
    print(res)
}

fun(3,3,3)

[1] 6


In [18]:
#Calling a Function with Default Argument

new_fun <- function(a=1, b=4) {
    res <- a/b
    print(res)
}

new_fun()

[1] 0.25


In [19]:
new_fun(8)

[1] 2


In [20]:
new_fun(,9)

[1] 0.1111111


### Lazy Evaluation of Function

In [21]:
#Arguments to functions are evaluated lazily, which means so they are evaluated only when needed by the function body.

lazy_fun <- function(a, b){
    print(a^2)
    print(a)
    print(b)
}

#call the function // this is lazy function because Evaluate the function without supplying one of the arguments.
lazy_fun(6)

[1] 36
[1] 6


ERROR: Error in print(b): argument "b" is missing, with no default


### Vectorized operation

In [23]:
x <- matrix(1:4, 2,2); y <- matrix(rep(10, 4), 2,2)

x
y
print('-----------------Here the Result of Multiplication of two matrix--------------------------------')
x* y # it will perform the dot matix multiplication mean/ one value with the one value of column of other matrix

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 10   10  
[2,] 10   10

[1] "-----------------Here the Result of Multiplication of two matrix--------------------------------"


[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [25]:
print("--------------Result------------")
x/y  # it will divide the matrix 

[1] "--------------Result------------"


[,1] [,2]
[1,] 0.1  0.3 
[2,] 0.2  0.4

In [30]:
print("---------Result of true Multiplication----------------")
print(x , y)
x %*% y

[1] "---------Result of true Multiplication----------------"
     [,1] [,2]
[1,]    1    3
[2,]    2    4


[,1] [,2]
[1,] 40   40  
[2,] 60   60

### Date & Time

In [33]:
# to retrive systme time we use below function

x <- Sys.time()

print(x)

[1] "2021-03-22 13:19:02 PKT"


In [34]:
class(x)

[1] "POSIXct" "POSIXt"

In [35]:
x$sec

ERROR: Error in x$sec: $ operator is invalid for atomic vectors


In [36]:
p <- as.POSIXlt(x)

In [37]:
p

[1] "2021-03-22 13:19:02 PKT"

In [38]:
p$sec

[1] 2.485322

In [39]:
p$hour

[1] 13

In [41]:
names(unclass(p))

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

In [42]:
p$gmtoff

[1] 18000

In [43]:
p$zone

[1] "PKT"

In [44]:
# strptime format

date_string <- c("January 10, 2012 10:40", "December 9, 2011 9:10")

In [49]:
x <- strptime(date_string, "%B %d, %Y %H:%M" )

In [50]:
x

[1] "2012-01-10 10:40:00 PKT" "2011-12-09 09:10:00 PKT"

In [51]:
class(x)

[1] "POSIXlt" "POSIXt"

In [66]:
# Methematical operation on data.

x <- as.Date("2012-01-01")
y <- strptime("9 jan 2011 11:34:21", "%d %b %Y %H:%M:%S")

x-y

Warning message in eval(expr, envir, enclos):
"Incompatible methods ("-.Date", "-.POSIXt") for "-""

ERROR: Error in x - y: non-numeric argument to binary operator


In [67]:
class(x)

[1] "Date"

In [68]:
class(y)

[1] "POSIXlt" "POSIXt"

In [69]:
x <- as.POSIXlt(x)

In [70]:
x-y

Time difference of 356.7261 days

## Loop Function

### Lapply function

In [73]:
# lapply always return the list

x <- list(a = 1:4, b= rnorm(15))
x

$a
[1] 1 2 3 4

$b
 [1] -0.24494501  0.15666651  0.27009056 -1.04122475  0.35517424 -2.52494564
 [7]  0.08057436 -0.57766002 -0.20753908  2.09573648 -0.58302681  0.76346060
[13] -1.31306358 -1.10469705  0.46349717

In [75]:
lapply(x, sum)

$a
[1] 10

$b
[1] -3.411902

In [76]:
class(x)

[1] "list"

In [79]:
X <- list(a = 1:5, b= rnorm(10), c= rnorm(20,1), d = rnorm(100,5))

X

$a
[1] 1 2 3 4 5

$b
 [1]  0.02208239  0.62595415 -1.50044209 -1.35904067 -0.07302853  0.12757305
 [7] -0.75964448  0.50764128 -0.54053604  1.57023692

$c
 [1]  1.6299763  0.7456602  1.1204956  1.1663003  1.4329614  1.5470075
 [7]  1.0474631  0.8507274  1.2965347  1.3545348  0.6657628  1.2750117
[13]  0.6001926  1.5750896 -0.1303263  1.9554651  1.1748620  2.3440069
[19] -0.5753386  1.6900859

$d
  [1] 3.904302 4.183020 4.439406 4.958892 4.962032 6.443585 3.801246 4.118776
  [9] 4.712259 5.178317 6.207362 4.429952 5.179148 5.737893 4.861514 6.343389
 [17] 4.568496 4.577702 3.802457 4.339527 4.603654 5.751229 3.418699 5.227511
 [25] 6.111551 5.284702 5.555760 4.799628 2.838216 7.211030 6.992484 5.557666
 [33] 6.015591 2.536439 3.648320 3.134033 5.890572 4.310643 5.695872 5.439111
 [41] 4.008487 4.865455 4.699238 4.433303 4.636607 5.706131 2.812272 5.110994
 [49] 4.841963 5.755352 2.590199 5.567133 2.992320 4.677264 5.516393 4.117708
 [57] 4.755146 4.984434 5.564471 5.830284 4.058184 4.839883 5.516856 5.934958
 [65] 4.217921 5.899926 4.886801 3.196772 4.774775 5.703837 4.281650 5.953470
 [73] 5.075536 4.641983 5.378306 5.816825 6.128048 6.537657 5.729103 4.481730
 [81] 4.522553 4.639474 4.628710 4.454901 6.123223 3.354679 6.027079 4.764153
 [89] 4.824347 4.223936 4.391973 4.957369 4.241350 3.877912 5.576001 5.328119
 [97] 5.092481 3.761396 4.887130 4.066423

In [80]:
class(X)

[1] "list"

In [82]:
lapply(X, mean)

$a
[1] 3

$b
[1] -0.1379204

$c
[1] 1.138324

$d
[1] 4.870346

In [85]:
lapply(X, sd)

$a
[1] 1.581139

$b
[1] 0.937763

$c
[1] 0.6692185

$d
[1] 0.9532313

In [86]:
lapply(X, max)

$a
[1] 5

$b
[1] 1.570237

$c
[1] 2.344007

$d
[1] 7.21103

In [87]:
# another example

x <- 1:4

lapply(x, runif)

[[1]]
[1] 0.6348295

[[2]]
[1] 0.1159926 0.9083128

[[3]]
[1] 0.7581624 0.1162935 0.6517414

[[4]]
[1] 0.5521164 0.9815288 0.3531542 0.1909592

In [95]:
x <- 1:4


lapply(x, runif, min=10, max=12)

[[1]]
[1] 10.03416

[[2]]
[1] 10.90029 11.63173

[[3]]
[1] 11.96368 11.91573 11.46002

[[4]]
[1] 11.36784 10.45970 11.45432 10.93610

### sapply

In [97]:
#This is the advanced version

In [107]:
x <- list(a = 1:4, b = rnorm(10), c=rnorm(20,1), d= rnorm(10,4))
x
sapply(x, mean)

$a
[1] 1 2 3 4

$b
 [1] -0.73170648  0.45244318 -1.82298737 -0.07480359  0.44578938 -0.60010870
 [7] -0.54366588  1.47023992 -0.69571532  0.71183437

$c
 [1]  0.60823606  0.87081548  1.87734221  0.62453396  1.92205540  3.13953158
 [7]  0.33229903 -0.75427445 -0.05073317 -0.83260410  1.46088492  0.58068579
[13]  2.08558446  0.96434263  2.89322239  0.69805144 -0.62755676  1.01786856
[19]  0.99609745  0.76131709

$d
 [1] 4.168111 4.078033 4.156238 4.270045 2.631620 3.951083 4.774235 2.224449
 [9] 1.967312 4.580572

a         b         c         d 
 2.500000 -0.138868  0.928385  3.680170

In [108]:
sapply(x, sum)

a        b        c        d 
10.00000 -1.38868 18.56770 36.80170

## apply function of loop

# example of apply function

x <- matrix(rnorm(200), 20, 10)
x

In [113]:
apply(x, 1, sum) # here is x, margin(row =1 or column = 2, sum)

[1] -5.995582431  0.315981515  3.219249273 -3.908864892 -2.004033800
 [6]  0.693968799 -2.272833870  4.940617720 -4.307564151  1.833418138
[11]  0.740457039  0.326121493 -3.585312755  1.649642853  4.314568933
[16] -2.262833552  2.116600054  2.076920133 -1.231757128  0.006249346

In [114]:
apply(x,2, sum)

[1]  2.0929361  8.5269620 -0.6400445  2.0231789 -2.3286811 -2.4130417
 [7] -1.2682116 -1.4141027 -1.0564352 -6.8575475

In [116]:
#Aonther method of to use Margin

rowSums(x) # similar like above example

[1] -5.995582431  0.315981515  3.219249273 -3.908864892 -2.004033800
 [6]  0.693968799 -2.272833870  4.940617720 -4.307564151  1.833418138
[11]  0.740457039  0.326121493 -3.585312755  1.649642853  4.314568933
[16] -2.262833552  2.116600054  2.076920133 -1.231757128  0.006249346

In [117]:
colSums(x) #similar to apply(x, 2, sum)

[1]  2.0929361  8.5269620 -0.6400445  2.0231789 -2.3286811 -2.4130417
 [7] -1.2682116 -1.4141027 -1.0564352 -6.8575475

### Quantiles

In [122]:
apply(x, 2, quantile)

[,1]       [,2]       [,3]        [,4]       [,5]        [,6]      
0%   -1.5365199 -0.8974687 -1.52711520 -1.0330638 -2.20669938 -1.9840446
25%  -0.9120765 -0.0127499 -0.73648237 -0.7722936 -0.99160047 -1.2045372
50%   0.1335768  0.4238222 -0.02458165  0.1839539  0.03316682 -0.1151703
75%   0.5690778  0.9372129  0.32491541  0.6598318  0.65852405  0.5003678
100%  2.7882945  1.5890612  1.45290775  2.4462523  2.15707635  3.2500079
     [,7]         [,8]        [,9]        [,10]     
0%   -1.880055955 -1.80901267 -2.10701376 -1.7624934
25%  -0.500845166 -0.44947000 -0.69241286 -1.0829735
50%  -0.002705438 -0.09144545  0.05582733 -0.3525981
75%   0.531950356  0.28676753  0.63438924  0.4467944
100%  2.082084676  1.75796498  1.63607025  0.9394386

### Tapply function

In [133]:
# example of tapply

x <- c(rnorm(10), runif(10), rnorm(10,1))

f <-gl(3,10)
f

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

In [134]:
tapply(x,f, mean)

1         2         3 
0.3426487 0.3485618 1.4925086

In [135]:
tapply(x,f,sum, simplify = TRUE)

1         2         3 
 3.426487  3.485618 14.925086

In [139]:
x
f
tapply(x, f, range, simplify = TRUE)

[1] -0.14671786  1.11722678  1.27135645  1.50379403  0.17166631 -0.06365639
 [7]  1.12301153 -0.58267187  0.66852717 -1.63604934  0.65928543  0.11196866
[13]  0.48342230  0.46672361  0.11570913  0.13889582  0.07587685  0.58923926
[19]  0.61766777  0.22682937  0.51215551  2.12952138  0.23442941  2.18294626
[25]  1.54545296  2.08426924  1.20093482  1.21076990  1.54263946  2.28196658

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

$`1`
[1] -1.636049  1.503794

$`2`
[1] 0.07587685 0.65928543

$`3`
[1] 0.2344294 2.2819666

## Data Split

In [9]:
# data split example

x <- c(rnorm(10), runif(10), rnorm(10))

f <- gl(3,10)
x
f

split(x,f)



[1]  0.6756906  1.0669449 -0.2891200  1.2452895 -1.3066758 -0.2765923
 [7]  0.1944742  1.8133957 -0.2853977  0.3588855  0.1391241  0.5405766
[13]  0.4015625  0.8196249  0.2410534  0.6314191  0.2819950  0.3684119
[19]  0.7687167  0.3854859 -1.7066544  1.1478690  0.2527261  1.1293464
[25] -1.2654172 -0.7557295 -0.9511382 -0.2415696  2.4850883 -0.4477509

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

$`1`
 [1]  0.6756906  1.0669449 -0.2891200  1.2452895 -1.3066758 -0.2765923
 [7]  0.1944742  1.8133957 -0.2853977  0.3588855

$`2`
 [1] 0.1391241 0.5405766 0.4015625 0.8196249 0.2410534 0.6314191 0.2819950
 [8] 0.3684119 0.7687167 0.3854859

$`3`
 [1] -1.7066544  1.1478690  0.2527261  1.1293464 -1.2654172 -0.7557295
 [7] -0.9511382 -0.2415696  2.4850883 -0.4477509

In [11]:
# A common idiom is split followed by an lapply

lapply(split(x,f), mean)

$`1`
[1] 0.3196895

$`2`
[1] 0.457797

$`3`
[1] -0.035323

In [13]:
# data set of airqaulity

library(datasets)
head(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [16]:
s <- split(airquality, airquality$Month)

lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R","Wind")]))

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800

In [18]:
sapply(s, function(x) colMeans(x[,c("Ozone","Solar.R","Wind")]))

5        6         7          8        9       
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800

In [20]:
# to get best result then remove the Null values

sapply(s, function(x) colMeans(x[,c("Ozone", "Solar.R", "Wind")], na.rm=TRUE))

5         6         7          8          9        
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000